import os
from datetime import datetime

# Absolute project root (same pattern as other agents)
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

class ReportBuilder:
    def __init__(self):
        # Force outputs directory into project root
        self.output_dir = os.path.join(PROJECT_ROOT, "outputs")
        os.makedirs(self.output_dir, exist_ok=True)

    def build_report(self, session_id, cleaned_df, stats, plots, insights, session_folder):
        """
        Creates a final markdown report that includes:
        - Overview
        - Basic stats
        - Business insights
        - Plot references
        """

        # Save report *inside the session folder*
        report_path = os.path.join(session_folder, "report.md")

        with open(report_path, "w", encoding="utf-8") as f:

            # Title
            f.write(f"# BI Analysis Report — Session {session_id}\n\n")

            # Section 1: Overview
            f.write("## 1. Overview\n")
            f.write(f"- Total rows after cleaning: **{cleaned_df.shape[0]}**\n")
            f.write(f"- Total columns: **{cleaned_df.shape[1]}**\n\n")

            # Section 2: Basic Statistics
            f.write("## 2. Summary Statistics\n")
            f.write("```\n")
            f.write(str(cleaned_df.describe(include='all')))
            f.write("\n```\n\n")

            # Section 3: Business Insights
            f.write("## 3. Business Insights\n")
            f.write("\n".join(insights))
            f.write("\n\n")

            # Section 4: Plots
            f.write("## 4. Visualizations\n")
            f.write("Below are the visualizations generated by the EDA agent:\n\n")
            for p in plots:
                f.write(f"- {p}\n")

        return report_path
